# Generated by Django 4.2 on 2023-04-19 02:11

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(regex='[986][0-9]{7}')])),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('evidence', models.FileField(upload_to='uploads/issues/%Y/%m/%d')),
                ('submit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date submitted')),
                ('type', models.CharField(choices=[('Facilities', 'Facilities'), ('Road', 'Road'), ('Sewerage', 'Sewerage'), ('Others', 'Others')], default='Others', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Open', 'Open'), ('Resolved', 'Resolved')], default='Open', max_length=8)),
            ],
        ),
    ]
