# Generated by Django 4.2 on 2023-04-19 03:30

from django.db import migrations, models
import govtech_csg_acas.securefileupload.validators


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='evidence',
            field=models.FileField(upload_to='uploads/issues/%Y/%m/%d', validators=[govtech_csg_acas.securefileupload.validators.acas_file_validator]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
